### ISSUE TITLE
Using the mouse

### ISSUE THREAD

**Issue by jgarte** [galeo/corfu-doc#10]
Is it possible to [scroll the documentation](https://github.com/galeo/corfu-doc#scroll-the-documentation) with the mouse wheel?

I'd also like to be able to [toggle the documentation](https://github.com/galeo/corfu-doc#quickly-toggle-the-documentation-on-or-off) by clicking the middle mouse button.

**Comment by galeo** [comment]
> Is it possible to [scroll the documentation](https://github.com/galeo/corfu-doc#scroll-the-documentation) with the mouse wheel?

I think it should work, but maybe not very well. Scrolling may cause the completion frame to disappear.

> I'd also like to be able to [toggle the documentation](https://github.com/galeo/corfu-doc#quickly-toggle-the-documentation-on-or-off) by clicking the middle mouse button.

You can try to bind `<mouse-2>` to command `corfu-doc-toggle`.

I don't think there's any advantage to using the mouse, as the need to switch between keyboard and mouse will definitely have some impact.
