### ISSUE TITLE
`corfu`, `corfu-doc` and `corfu-terminal`

### ISSUE THREAD

**Issue by AkibAzmain** [galeo/corfu-doc#12]
Hi,

I'm the author of `corfu-terminal`.  `corfu-terminal` allows to use Corfu on terminal.  I'm trying to make `corfu-doc` working in terminal, but I can't find any sane way to do this, because `corfu-doc` depends heavily on the window of child frame.  For Corfu, it was easy because though it uses child frame, it is line oriented.

Can you help to `corfu-doc` usable on terminal?  One solution would be to use `corfu--popup-show` and `corfu--popup-hide` but that might be too specialized for Corfu to use.  Another solution would be to not depend on the window of child frame, instead be line oriented like Corfu and rewrite the doc buffer (the buffer visible in the child frame) for every change (e.g. scroll, candidate change) using a function to show the popup and another to hide it.  Then I can write a package like `corfu-doc-terminal` and override those functions that show and hide the popup.  If you don't do anything, then another package must be developed from scratch for doing the same work but with terminal support, which is indeed undesirable.

**Comment by galeo** [comment]
There may be some problems with using overlay to implement the document popup. I have encountered it before. The famous auto-complete.el (depending on popup.el) and company-quickhelp.el often cause glitches. You can take a look at their issue list, lots of unfixed bugs. There are also performance issues brought by overlay. So I agree with @minad's idea, in the terminal, you can use the document buffer instead. 

I talked to minad about future plans for corfu-doc to be added to corfu as an extension. Please see #8.

Thanks.

**Comment by AkibAzmain** [comment]
> There may be some problems with using overlay to implement the document popup. I have encountered it before. The famous auto-complete.el (depending on popup.el) and company-quickhelp.el often cause glitches. You can take a look at their issue list, lots of unfixed bugs.

I don't know about `auto-complete`, but I do know that `company-quickhelp-terminal` (assuming you meant this by saying `company-quickhelp`) have many problems, and I also know the cause, it's because `company` creates the popup using its own popup code and `company-quickhelp-terminal` creates the popup with `popup.el`, which fight with each other.

And I also have a solution: Popon.  Popon is a library similar to `popup` but minimal.  My `corfu-terminal` uses Popon library instead of doing itself, so another popup can be shown with Popon without causing problem.

> There are also performance issues brought by overlay. So I agree with @minad's idea, in the terminal, you can use the document buffer instead.

The performance issue isn't a big deal on terminal.

But no, I didn't say that you should use overlay to show the popup.  I just said that instead of the interacting with the child frame directly, write a few dedicated functions for the popup which takes what to show.  For example:

```emacs-lisp
(defun hide-popup ()
  "Hide popup."
  ...)

(defun show-popup (content scroll width height)
  "Show a WIDTHxHEIGHT popup with CONTENT and scroll to SCROLLth line.

If CONTENT is nil, use the previous contents."
  ...)

(show-popup "foo:\nDo foo.\nAnd return." 1 15 2)
;; Popup:
;; +---------------+
;; |foo:           |
;; |Do foo.        |
;; +---------------+

(show-popup nil 2 10 1)
;; Popup:
;; +---------------+
;; |Do foo.        |
;; |And nothing.   |
;; +---------------+
```

Then I can easily override the popup functions to make it Popon on terminal.  And please don't call `display-graphic-p` directly, use another function for that (Corfu has `corfu--popup-support-p`) so that I can easily override it.

> 
> I talked to minad about future plans for corfu-doc to be added to corfu as an extension. Please see #8.

Yeah, I know that.  I also have plan to write a package `corfu-doc-terminal` and add it to `corfu-terminal` once your package is added to Corfu.

> 
> Thanks.

**Comment by galeo** [comment]
> I don't know about `auto-complete`

You can see it [here](https://github.com/auto-complete/auto-complete). 

I did not say it clearly, `company-quickhelp.el` uses `pos-tip` to display. I've followed a lot of discussions about displaying popups in the terminal before. Some problems are actually difficult to solve due to practical limitations.

> And I also have a solution: Popon. Popon is a library similar to `popup` but minimal. My `corfu-terminal` uses Popon library instead of doing itself, so another popup can be shown with Popon without causing problem.

Could you give some comparisons about Popon and popup.el? Such as its improvements and advantages over popup.el. Or you can write these into Popon's introduction.

> But no, I didn't say that you should use overlay to show the popup. I just said that instead of the interacting with the child frame directly, write a few dedicated functions for the popup which takes what to show.

I'll take a look and consider refactoring the code according to the way you describe. But probably not particularly fast, I've been busy with some other things lately.

Thanks.

**Comment by AkibAzmain** [comment]
> > I don't know about `auto-complete`
> 
> You can see it [here](https://github.com/auto-complete/auto-complete).

I mean I don't know what problems it cause, because I never used this.

> 
> I did not say it clearly, `company-quickhelp.el` uses `pos-tip` to display. I've followed a lot of discussions about displaying popups in the terminal before. Some problems are actually difficult to solve due to practical limitations.

Yeah, someone should implement child frames on terminal, which will solve all problems.

> 
> Could you give some comparisons about Popon and popup.el? Such as its improvements and advantages over popup.el. Or you can write these into Popon's introduction.

The main difference is that Popon is inspired by child frames.  Just like child frames, a Popon doesn't move with scrolling or buffer switch.  However, it can't cross window border, as it is implemented using overlays.  And Popon doesn't touch the buffer text at all, while I've seen that sometimes `popup-el` changes buffer text when error occurs.

> 
> I'll take a look and consider refactoring the code according to the way you describe. But probably not particularly fast, I've been busy with some other things lately.
> 
> Thanks.

Thanks.

**Comment by galeo** [comment]
@AkibAzmain 

The pull request has been merged, please comment if needed and we can reopen this issue.

Thanks.

**Comment by minad** [comment]
@galeo Do you still plan to add your package to Corfu itself as an extension? I would be interested in having it there. However my requirement for addition is that the child frame is shared with Corfu. This requires some refactoring in Corfu itself to make the child frame code a bit more flexible such that it can handle multiple popups.

**Comment by minad** [comment]
Maybe we could also do this in small steps, getting rid of the adapted functions one by one.

https://github.com/galeo/corfu-doc/blob/611895ef47a22c1ba0142d6cda60cf56a99adf15/corfu-doc.el#L148

Regarding focus redirection, I changed the approach:

https://github.com/galeo/corfu-doc/blob/611895ef47a22c1ba0142d6cda60cf56a99adf15/corfu-doc.el#L143-L146

https://github.com/minad/corfu/commit/77932f45ce98dfc3e9f00f451af29433c3b241c9

It works much better like this! I suggest you change corfu-doc accordingly.

Instead of `corfu-doc--popup-support-p` why not just use `corfu--popup-support-p`? Why the code duplication?

**Comment by galeo** [comment]
> Do you still plan to add your package to Corfu itself as an extension?

Yes.

> However my requirement for addition is that the child frame is shared with Corfu. This requires some refactoring in Corfu itself to make the child frame code a bit more flexible such that it can handle multiple popups.

I'm starting to prepare to refactor the code. I'll make a pull request later.

Thanks.

**Comment by minad** [comment]
Okay, take your time. I won't be able to look at this for another week. Please make sure to split the refactorings in separate commits which can be checked independently if that's possible. I hope that the complexity in corfu.el doesn't go up to much.
