### ISSUE TITLE
Reccommended key bindings are backwards?

### ISSUE THREAD

**Issue by antler5** [galeo/corfu-doc#15]
```
(define-key corfu-map (kbd "M-p") #'corfu-doc-scroll-down) ;; corfu-next
(define-key corfu-map (kbd "M-n") #'corfu-doc-scroll-up)  ;; corfu-previous
```

Hi! I guess this might be a matter of perspective, but these binds feel backwards to me; `corfu-next` advances down to the next selection, which does correspond to `corfu-doc-scroll-down`, but would conventionally be bound to `M-n` (`n` for next), not `M-p` (and vice versa).

**Comment by galeo** [comment]
You may want have a look at the `scroll-up` and `scroll-down` commands. Scroll the content up or down. The line end comment indicates the command to which the corresponding key was originally bound.
