### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by minad** [galeo/corfu-doc#16]
Hey @galeo,

in preparation of https://github.com/minad/corfu/pull/178 I tested your package more thoroughly. Overall, this is great work! I observed a few issues which should be resolved first before merging this into Corfu itself:

- [X] When scrolling over candidates the doc frame flickers heavily. It always redisplays once without content and then with content. Is there a chance to improve this such that the content is displayed immediately?

- [X] There are multiple missing docstrings and other warnings which should be sorted out. Check out package-lint.

- [x] The option corfu-doc-display-within-parent-frame is set to nil by default. This option does not work on most platforms, in particular not on the free ones. I suggest we remove the option entirely and always display the frame inside the parent frame. This should also simplify the position computation slightly.

- [x] You define a variable space=1 in `corfu-doc--calculate-doc-frame-position` such that the frames have a distance of 1. Did you consider instead to move the frames very close to each other space=-1, such that they share the border. This looks better in my opinion. (EDIT: Fixed, but we should also handled border width /= 1.)

- [x] Sometimes the child frame size fluctuates slightly when scrolling. This is probably related to the redisplay issue when scrolling.

- [ ] You use advices to hook into Corfu. Would it be possible to instead register a post-command-hook and then perform the required updates there, depending on if the corfu--frame is alive, the selected candidate etc? This seems a little bit cleaner.

**Comment by galeo** [comment]
> When scrolling over candidates the doc frame flickers heavily. It always redisplays once without content and then with content. Is there a chance to improve this such that the content is displayed immediately?

> Sometimes the child frame size fluctuates slightly when scrolling. This is probably related to the redisplay issue when scrolling.

The frame flicker issue should be fixed via 0c5bd800f689f4af765eb267df038d8068516a6e.

> The option corfu-doc-display-within-parent-frame is set to nil by default. This option does not work on most platforms, in particular not on the free ones. I suggest we remove the option entirely and always display the frame inside the parent frame. This should also simplify the position computation slightly.

I used the mac port version of emacs when I first wrote this package. This option was introduced later and is set to `nil` by default for compatibility. I would like to keep this option and set its value to `t`.

> You define a variable space=1 in corfu-doc--calculate-doc-frame-position such that the frames have a distance of 1. Did you consider instead to move the frames very close to each other space=-1, such that they share the border. This looks better in my opinion.

Yes, this can be considered. I'll update its value in the pull request (minad/corfu#178) later.


> You use advices to hook into Corfu. Would it be possible to instead register a post-command-hook and then perform the required updates there, depending on if the corfu--frame is alive, the selected candidate etc? This seems a little bit cleaner.

At the beginning of the implementation, consider when to show and hide the doc popup and for simplicity, it feels easier to use advices. I will try if this can be made cleaner by registering a post-command-hook.


> There are multiple missing docstrings and other warnings which should be sorted out. Check out package-lint.

I originally wanted to wait until you have reviewed the pull request, and if there are no problems, then add the docstrings. The other warnings has been resolved in the pull request. The `corfu-doc.el` code here is not the latest, you can comment directly in minad/corfu#178.

**Comment by minad** [comment]
> I used the mac port version of emacs when I first wrote this package. This option was introduced later and is set to nil by default for compatibility. I would like to keep this option and set its value to t.

Yes, I understand. I have to think about it. I have no ability to test this functionality and I am generally hesitant to support features which work better (or even work only!) on non-free platforms. I consider this a no go.

> At the beginning of the implementation, consider when to show and hide the doc popup and for simplicity, it feels easier to use advices. I will try if this can be made cleaner by registering a post-command-hook.

I hope that a pch will make this more clean.

> I originally wanted to wait until you have reviewed the pull request, and if there are no problems, then add the docstrings. The other warnings has been resolved in the pull request. The corfu-doc.el code here is not the latest, you can comment directly in https://github.com/minad/corfu/pull/178.

Your changes to corfu.el are mostly okay, but corfu-doc.el needs more work before it can be merged. I thought about first merging the corfu.el changes step by step and then I will review corfu-doc.el in greater detail. The warnings should be fixed anyway before the merge, so you can do that now or later.

**Comment by minad** [comment]
Regarding the flicker - I tried again.

- In the case of `corfu-doc-delay=nil` it doesn't flicker. However scrolling becomes quite slow since the documentation fetching is expensive. For my taste it feels too sluggish to use this by default.

- In the case of `corfu-doc-delay=0.1` it flickers. When scrolling the documentation popup is cleaned and then updated after 0.1s. It is not really flicker but it bothers me that I see the empty popup. I wonder if we could do better, e.g., retain the documentation relevant to the previous candidate and update after 0.1s with the new documentation.

- For `corfu-doc-delay>0.5` the popup is even deleted and then displayed again. This seems okay for large delays.

**Comment by galeo** [comment]
> Yes, I understand. I have to think about it. I have no ability to test this functionality and I am generally hesitant to support features which work better (or even work only!) on non-free platforms. I consider this a no go.

I have made the option default to =t=. The documentation mentions that since NS builds do not clip child frames at the parent frame's edges, I think this option can be considered.

> I hope that a pch will make this more clean.

I find it hard to define a pch without knowing when the corfu popup will show up. Can corfu itself provide a post popup show hook and a post popup hide hook?

> The warnings should be fixed anyway before the merge, so you can do that now or later.

Done now.

**Comment by minad** [comment]
> I have made the option default to =t=. The documentation mentions that since NS builds do not clip child frames at the parent frame's edges, I think this option can be considered.

Sure, I am considering it. But we should maybe reject it. There are two options:

1. Either it is possible to implement non-clipping child frames on X11/pgtk too. If that's the case it makes sense to add the feature to Corfu. But then one should first coordinate with upstream such that this is going to be implemented.
2. Or it is not possible to implement non-clipping child frames on X11/pgtk. Then it does not make sense to add this option.

> I find it hard to define a pch without knowing when the corfu popup will show up. Can corfu itself provide a post popup show hook and a post popup hide hook?

The idea would be the following - add a hook to completion-in-region-mode and install the pch there. The completion-in-region-mode will be enabled/disabled together with the corfu-map. In the pch one can then check the selected candidate and the existence of the popup.

> Done now.

Great, thanks!

**Comment by galeo** [comment]
> In the case of `corfu-doc-delay=nil` it doesn't flicker. However scrolling becomes quite slow since the documentation fetching is expensive. For my taste it feels too sluggish to use this by default.

I think the doc popup should be displayed in a synchronous way. On this premise, we can consider improving the performance, such as prefetching or caching under certain conditions.

> In the case of corfu-doc-delay=0.1 it flickers. When scrolling the documentation popup is cleaned and then updated after 0.1s. It is not really flicker but it bothers me that I see the empty popup. I wonder if we could do better, e.g., retain the documentation relevant to the previous candidate and update after 0.1s with the new documentation.

When `corfu-doc-delay=0.1`, only the popup content flashes. This is why I introduced the `corfu-doc-hide-threshold` option earlier. By setting the value of `corfu-auto-delay` reasonably, the flicker of the popup itself can be reduced as much as possible. If the latency is small, it is reasonable to consider retaining the documentation relevant to the previous candidate. However, doing so may be considered an error or bug if the delay is large.

**Comment by minad** [comment]
> When corfu-doc-delay=0.1, only the popup content flashes. This is why I introduced the corfu-doc-hide-threshold option earlier. By setting the value of corfu-auto-delay reasonably, the flicker of the popup itself can be reduced as much as possible. If the latency is small, it is reasonable to consider retaining the documentation relevant to the previous candidate. However, doing so may be considered an error or bug if the delay is large.

Yes sure, only the popup content flashes. I think for small delays retaining the content would be better. And for longer delays hiding the popup altogether seems like the best solution.

**Comment by galeo** [comment]
> I think for small delays retaining the content would be better. And for longer delays hiding the popup altogether seems like the best solution.

What kind of delay is small or longer? Later we can consider adding new options for users to choose from.

**Comment by minad** [comment]
> What kind of delay is small or longer? Later we can consider adding new options for users to choose from.

Yes, I would add an option for that.

**Comment by galeo** [comment]
> There are two options:
> 
>     1. Either it is possible to implement non-clipping child frames on X11/pgtk too. If that's the case it makes sense to add the feature to Corfu. But then one should first coordinate with upstream such that this is going to be implemented.
> 
>     2. Or it is not possible to implement non-clipping child frames on X11/pgtk. Then it does not make sense to add this option.

I agree. Can you help communicate with upstream?

**Comment by minad** [comment]
> I agree. Can you help communicate with upstream?

Yes, I can help with that. For now I'd say we go on and remove the option, but offer an easy way to override the display area, such that we have an easy upgrade path independent of the outcome of the discussion. See my comment https://github.com/minad/corfu/pull/178#discussion_r889666287.

**Comment by galeo** [comment]
@minad Since corfu already has the new extension corfu-docframe, I plan to make corfu-doc obsolete. I don't have much experience, can you help with a pull request? Then, I will archive this repository and make a pull request to remove corfu-doc from melpa. Thanks.

**Comment by minad** [comment]
My suggestion is to add a warning message to the package, telling the
user to migrate. After waiting another three months, archive the
repository and remove it from MELPA.

cc @tarsius Does this sound like a reasonable migration strategy for a
package?

**Comment by AkibAzmain** [comment]
I'm going to stick to this for now, please add an user option to inhibit such warning.

**Comment by tarsius** [comment]
> cc [@tarsius](https://github.com/tarsius) Does this sound like a reasonable migration strategy for a package?

If I remember correctly, we Melpa folks have a one recommended approach we always suggest, and leave it to the package maintainer to decide what is best. This sounds like a reasonable approach. (Personally I lean towards the "rip of the bandage" approach.)

I have suggested that `package.el` should learn to handle package renames, see https://lists.gnu.org/archive/html/emacs-devel/2022-11/msg00978.html. I'll add a note about packages that have been absorbed.

**Comment by galeo** [comment]
@tarsius Thanks. I just submitted a pull request #24 to deprecate this package. Then after a while, try to remove it from MEPLA.

**Comment by minad** [comment]
I believe all of the issues I mentioned in my initial comment here are addressed in the new  corfu-popupinfo. Closing.
