### ISSUE TITLE
emacs-daemon won't start after the latest update

### ISSUE THREAD

**Issue by rrudakov** [galeo/corfu-doc#19]
Hello, I use emacs-daemon + emacsclient on Arch Linux. I usually run emacs using `systemctl --user start emacs.service`. After the latest update of `corfu-doc` I'm getting the error in logs:
```
Jun 06 10:52:36 rudakov-xps emacs[4841]: Warning (initialization): An error occurred while loading ‘/home/rrudakov/.emacs.d/init.el’:
Jun 06 10:52:36 rudakov-xps emacs[4841]: error: Corfu-doc requires child frames to display documentation
Jun 06 10:52:36 rudakov-xps emacs[4841]: To ensure normal operation, you should investigate and remove the
Jun 06 10:52:36 rudakov-xps emacs[4841]: cause of the error in your initialization file.  Start Emacs with
Jun 06 10:52:36 rudakov-xps emacs[4841]: the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
Jun 06 10:52:36 rudakov-xps emacs[4841]: Package rfc2368 is deprecated
Jun 06 10:52:36 rudakov-xps emacs[4841]: Package cl is deprecated
```

Starting emacs without systemctl works fine.

**Comment by galeo** [comment]
Please have a try with the latest code and see if this issue has been resolved. Thanks.

**Comment by rrudakov** [comment]
Yeah, I can start the emacs-daemon now, thanks @galeo. Just wanna bring your attention to the fact that I see a log of similar warnings in the log now:
![warnings](https://user-images.githubusercontent.com/6093590/172232113-df02f834-31df-4285-9a49-fcf7d5c5bd8c.png)

`Warning (corfu-doc): Corfu-doc requires child frames to display documentation Disable showing Disable logging`

I'd expect one warning, but I see a lot, can it be some issue?

**Comment by galeo** [comment]
I think you shouldn't turn on corfu-doc-mode when `(display-graphic-p)` returns `nil`.

**Comment by rrudakov** [comment]
I have the following configuration:
```emacs-lisp
(use-package corfu-doc
  :config
  (customize-set-variable 'corfu-doc-delay 1)
  (customize-set-variable 'corfu-doc-max-width 500)
  (customize-set-variable 'corfu-doc-max-height 30)
  (add-hook 'corfu-mode-hook #'corfu-doc-mode))
```
And I also have `(global-corfu-mode)`, probably that's the problem, I'll try to enable corfu when the frame is created. Thanks for the tip.
