### ISSUE TITLE
Child frame not positioned correctly with external monitor

### ISSUE THREAD

**Issue by ashton314** [galeo/corfu-doc#2]
Hey there! I love this package!

I'm getting an issue with the child frame when Emacs is on my external monitor. Here's what it looks like:

<img width="2560" alt="Screen Shot 2022-01-03 at 16 51 13 (2)" src="https://user-images.githubusercontent.com/2874507/147992580-2bb707cc-dddf-4807-8882-449eeef7949c.png">

Is there anything else that I can contribute to help figure this out? I wouldn't call myself an elisp wizard or anything, but I can follow whatever instructions you give me. I'm sorry if this isn't too helpful. 🙁

**Comment by galeo** [comment]
> Hey there! I love this package!

Thanks.



> Is there anything else that I can contribute to help figure this out?

What's the output of `(display-monitor-attributes-list)`?

**Comment by ashton314** [comment]
```elisp
(((geometry 0 0 1440 900)
  (workarea 0 25 1440 875)
  (mm-size 285 179)
  (frames)
  (source . "NS"))
 ((geometry 1440 -483 2560 1440)
  (workarea 1440 -483 2560 1415)
  (mm-size 622 340)
  (frames #<frame *scratch* 0x7f8b0f055c30> #<frame  0x7f8b17a0ded8>)
  (source . "NS")))
```

**Comment by galeo** [comment]
Please have a try with 807af9f and see if the problem has been solved.

**Comment by ashton314** [comment]
Yes! That's working perfectly now 🙌🏼
