### ISSUE TITLE
How to move doc from corfu's popup to a buffer?

### ISSUE THREAD

**Issue by mekeor** [galeo/corfu-doc#22]
Hello, although corfu-doc allows scrolling of the doc, I'd sometimes prefer to just move the doc to a buffer and open/view it in the current window. How can I do that?

**Comment by galeo** [comment]
Corfu has a built-in extension [corfu-info.el](https://github.com/minad/corfu/blob/main/extensions/corfu-info.el) that you can take a look at.

**Comment by mekeor** [comment]
thank you! it works!

for the record: the corfu-info extension uses the same documentation function, so the docs are equal. in fact, if i see correctly, corfu-info is enabled by default, and bound to M-g and M-h.

**Comment by stevemolitor** [comment]
It'd be nice to hide corfu-doc when invoking corfu-info, to avoid corfu-doc overlaying the doc buffer:

![](https://cdn.zappy.app/737e0c007dd3d39af599b9609b50e08d.png)

**Comment by galeo** [comment]
Yes, I will keep this in mind.
