### ISSUE TITLE
Doc frame extends outside of view on monitor

### ISSUE THREAD

**Issue by stevemolitor** [galeo/corfu-doc#23]
I sometimes see completions like this, where the documentation frame is way to the left and cut off at the edge of my monitor:

![](https://cdn.zappy.app/5d8ad6f861a6be242536b060c9b7c9cc.png)

I've only seen this with cider, and mostly in the cider REPL as I recall.

I'm using Emacs 29 recent master on a MacOS M1 machine.

I tried with `corfu-doc-display-within-parent-frame` set to both `nil` and `t`; same result.

**Comment by galeo** [comment]
> I'm using Emacs 29 recent master on a MacOS M1 machine.

The position issue with multiple monitors was fixed before, see #2. I haven't tested it on Emacs 29. Does it work fine on Emacs 28? And what's the output of `(display-monitor-attributes-list)`?

**Comment by stevemolitor** [comment]
Thanks for the fast reply!

It does _not_ happen on Emacs 28:

![](https://cdn.zappy.app/f6a4d6aa076363ed0b64368d69ec79a8.png)

Also note that on Emacs 28 the cider window is _below_ the source window, whereas in Emacs 29 I see it to the right.

To clarify, I see the bug in Emacs 29 on my external monitor _and_ on my laptop with no external monitor connected.

## Output of `(display-monitor-attributes-list)` on Emacs 28

```emacs-lisp
(((geometry 0 0 2560 1440) (workarea 0 25 2560 1415) (mm-size 699 389) (frames #<frame  *Minibuf-1*      Oct 18 11:26 AM  0x1331c5e30> #<frame  0x178e48620> #<frame  0x13339f430>) (source . "NS")) ((geometry 2560 351 1728 1117) (workarea 2560 351 1728 1079) (mm-size 344 222) (frames) (source . "NS")))
```

## Output of `(display-monitor-attributes-list)` on Emacs 29

```emacs-lisp
(((geometry 0 0 2560 1440) (workarea 0 25 2560 1415) (mm-size 699 389) (frames #<frame  *Minibuf-1*      Oct 18 11:36 AM  0x12e98dc30> #<frame  0x146a9ab78> #<frame  0x11d27f158>) (source . "NS")) ((geometry 2560 351 1728 1117) (workarea 2560 351 1728 1079) (mm-size 344 222) (frames) (source . "NS")))
```

They look pretty much the same. 🤷 

In Emacs 29, if i mess with `display-buffer-alist` to display the cider repl below the source window it works fine, both using `(display-buffer-below-selected)` and display in a bottom side window:

![](https://cdn.zappy.app/6e8f66beef8407af9692aa955f3976ef.png)

So the issue seems to be the split window on the right side.

**Comment by galeo** [comment]
Thanks for the feedback. I'll test it on Emacs 29 when I have time.

**Comment by stevemolitor** [comment]
Update: On Emacs 28, I do not see the bug even when cider is in a right side window:

![](https://cdn.zappy.app/65d6b8725605e7e5663ebc55c517984a.png)

On Emacs 29 I also do _not_ see the bug if I have two sources windows side by side:

![](https://cdn.zappy.app/c09771dc19033087e9279124fc2af20c.png)

On Emacs 29 I also do not see the issue if cider is in a left side window:

![](https://cdn.zappy.app/86f29e1eaa66c298549335dad6ab05f6.png)

I only see the issue when all these things are true:

- Emacs 29
- Completing from cider in a window to the _right_

**Comment by galeo** [comment]
The position of the window should not cause this issue. It needs to calculate the position and size of the corfu child frame and the parent frame (display). Can you help test it on the X window system? It may be a bug introduced by Emacs 29.

**Comment by stevemolitor** [comment]
> Can you help test it on the X window system?

Sorry I only have a Mac machine (and don't have XQuartz setup).

Happy to provide any other debugging info though. I did briefly try stepping thru `corfu-doc--calc-popup-position` but quickly got overwhelmed!

**Comment by galeo** [comment]
This should be a bug of the NS port Emacs. I've submitted a bug report. On macOS, you can try the Mac port Emacs, it works fine.

**Comment by stevemolitor** [comment]
> This should be a bug of the NS port Emacs. I've submitted a bug report. On macOS, you can try the Mac port Emacs, it works fine.

Thanks for chasing this down! Do you have a link to the bug report so I can track it? Thanks!

**Comment by galeo** [comment]
It's [#58627](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=58627).

**Comment by galeo** [comment]
Hi @stevemolitor

This package is being merged into corfu as one of its extensions. [Here](https://github.com/minad/corfu/pull/178) is the pull request. I have tried adding a workaround for #58627 there. Would you like to try it out and see if it solves this problem? As a reminder, you need to patch `corfu.el`, and corfu-doc has been renamed to corfu-doc-popup.

**Comment by stevemolitor** [comment]
@galeo I tried your PR (via straight.el). I think it's fixed on NS Emacs 29:

![](https://cdn.zappy.app/5fc321d88595f4b9f35f321a89778539.png)

Thanks!

EDIT - updated photo, verifying a problem I had before with the overlay that seems to be fixed too. 

👍

**Comment by galeo** [comment]
OK. Thanks. I'll keep this issue open until the PR is merged.

**Comment by stevemolitor** [comment]
Thanks for the fix @galeo. Good stuff.

**Comment by galeo** [comment]
Close this issue, please use the new [corfu-docframe](https://github.com/minad/corfu/blob/main/extensions/corfu-docframe.el), which is an extension of corfu.
