### ISSUE TITLE
Relocate cache directory

### ISSUE THREAD

**Issue by krisbalintona** [galeo/corfu-doc#5]
Very fantastic work! I love the package.

I noticed that the package creates a .cache directory in the `emacs-directory` which stores SVG files. Though I'm not sure if this is directly from a setting this package set or a setting in another package this relies on, would it be possible to have a variable which chooses which directory is the cache?

**Comment by galeo** [comment]
> Very fantastic work! I love the package.

Thanks.

> I noticed that the package creates a .cache directory in the `emacs-directory` which stores SVG files. Though I'm not sure if this is directly from a setting this package set or a setting in another package this relies on

This package has nothing to do with svg. You should check other packages you use. Maybe `kind-icon`?  As far as I know, it can use icons in svg format.
