### ISSUE TITLE
Inconsistent behavior in corfu-doc-toggle

### ISSUE THREAD

**Issue by karthink** [galeo/corfu-doc#7]
Thanks for writing corfu-doc!

I noticed that the behavior of `corfu-doc-toggle` is inconsistent, in that it doesn't restore state correctly when you exit the Corfu completion. To reproduce this,

0. Make sure `corfu-doc-mode` is off.
1. Start a completion and call `corfu-doc-toggle`.
2. Cancel the completion session with `keyboard-quit`.
3. Start another completion. This time `corfu-doc--frame` pops up automatically because `corfu-doc-mode` was not turned off.

I modified this command to clean up after itself as follows:

```elisp
(defun corfu-doc--cleanup ()
  (advice-remove 'corfu--popup-hide #'corfu-doc--cleanup)
  (advice-remove 'corfu--popup-show #'corfu-doc--set-timer)
  (corfu-doc--hide))

(defun corfu-doc-toggle ()
  (interactive)
  (advice-add 'corfu--popup-hide :after #'corfu-doc--cleanup)
  (if (and corfu-doc--frame (frame-visible-p corfu-doc--frame))
      (progn (corfu-doc--hide)
             (advice-remove 'corfu--popup-show #'corfu-doc--set-timer))
    (corfu-doc--show)
    (advice-add 'corfu--popup-show :after #'corfu-doc--set-timer)))
```

If you want  to reuse `corfu-doc-mode` in `corfu-doc-toggle`, perhaps you could add an `unwind-protect` clause to this command instead?

**Comment by galeo** [comment]
Thanks. I've been a little busy recently. Would you like to make a pr?

**Comment by galeo** [comment]
> I noticed that the behavior of `corfu-doc-toggle` is inconsistent, in that it doesn't restore state correctly when you exit the Corfu completion.

What I originally thought was to quickly turn on and off `corfu-doc-mode` directly through this command because of performance issues in some cases.



> If you want to reuse `corfu-doc-mode` in `corfu-doc-toggle`, perhaps you could add an `unwind-protect` clause to this command instead?

```emacs-lisp
(defun corfu-doc-toggle (&optional arg)
  (interactive "P")
  (if (null arg)
      (setq arg (if corfu-doc-mode -1 1))
    (setq arg (prefix-numeric-value arg)))
  (unwind-protect
       (if (> arg 0)
           (corfu-doc-manually)
         (corfu-doc-hide))
    (corfu-doc-mode arg)))
```

Do you mean change it to this？

**Comment by karthink** [comment]
> Thanks. I've been a little busy recently. Would you like to make a pr?

Sure. Are you okay with the solution in my first post?

> Do you mean change it to this？

No, this still leaves `corfu-doc-mode` turned on after `keyboard-quit`. The `unwind-protect` will wrap almost the entire function, with `(corfu-doc-mode -1)` in the unwindform.

**Comment by galeo** [comment]
I'm not quite sure what you mean by inconsistent. `corfu-doc-toggle` actually turns the `corfu-doc-mode` on or off quickly. Maybe it would be better to change the doc string to "Toggle the corfu doc mode on or off" to make it clearer.

**Comment by karthink** [comment]
> Make sure corfu-doc-mode is off.
> Start a completion and call corfu-doc-toggle.
> Cancel the completion session with keyboard-quit. 
> Start another completion. This time corfu-doc--frame pops up automatically because corfu-doc-mode was not turned off.

In that case I take it this is intended behavior, please ignore my comment.

Is there a corfu-doc command I can use instead to generate a preview once (like `corfu-doc-manually`) that disappears when I move to the next candidate?

**Comment by galeo** [comment]
> Is there a corfu-doc command I can use instead to generate a preview once (like `corfu-doc-manually`) that disappears when I move to the next candidate?

I understand what you mean by now. At present, the doc popup is automatically displayed at a set delay.  The command `corfu-doc-manually` is used to quickly display the doc popup in some cases without waiting for delays. Or we can add a setting item to choose to display the doc popup  automatically or manually.

**Comment by galeo** [comment]
Hi @karthink 
Please try the latest code and see if it meets your needs. Thanks.
