### ISSUE TITLE
Release on ELPA/MELPA?

### ISSUE THREAD

**Issue by minad** [galeo/corfu-doc#8]

**Comment by galeo** [comment]
I prefer to release it on ELPA. I don't know exactly how to operate it. 
I've sent the GNU assignment pdf but haven't received a reply. So I'm waiting.

In fact, I want to add it to corfu as an extension. I don't write much emacs elisp code. The code quality may not be good enough, as well as the structure and interface design. This package reuses the code to create child frame and fetch candidate documentation from corfu. As you described [here](https://github.com/minad/corfu/issues/98#issuecomment-1000306821), the make frame api can be generalized. Corfu itself provides echo documentation buffer. Users can choose between these two ways. Are you willing to accept it as an extension of corfu?

**Comment by minad** [comment]
Yes I would accept it as an extension. We may have to clean up a few things here but I don't see a reason to keep it separately. I also plan to move out the doc buffer code so we could have two extensions: corfu-doc-popup and corfu-doc-buffer.
